# Generated by Django 2.0.1 on 2018-01-31 19:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Survey',
            new_name='ClientSurvey',
        ),
    ]
