# Generated by Django 2.0.1 on 2018-02-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20180131_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientsurvey',
            old_name='discription',
            new_name='description',
        ),
    ]
