# Generated by Django 2.0.1 on 2018-02-02 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20180201_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label1', models.CharField(blank=True, max_length=100, null=True)),
                ('imput1', models.CharField(blank=True, max_length=100, null=True)),
                ('label2', models.CharField(blank=True, max_length=100, null=True)),
                ('imput2', models.CharField(blank=True, max_length=100, null=True)),
                ('label3', models.CharField(blank=True, max_length=100, null=True)),
                ('imput3', models.CharField(blank=True, max_length=100, null=True)),
                ('label4', models.CharField(blank=True, max_length=100, null=True)),
                ('imput4', models.CharField(blank=True, max_length=100, null=True)),
                ('label5', models.CharField(blank=True, max_length=100, null=True)),
                ('imput5', models.CharField(blank=True, max_length=100, null=True)),
                ('label6', models.CharField(blank=True, max_length=100, null=True)),
                ('imput6', models.CharField(blank=True, max_length=100, null=True)),
                ('label7', models.CharField(blank=True, max_length=100, null=True)),
                ('imput7', models.CharField(blank=True, max_length=100, null=True)),
                ('label8', models.CharField(blank=True, max_length=100, null=True)),
                ('radio8', models.BooleanField(default=True)),
                ('label9', models.CharField(blank=True, max_length=100, null=True)),
                ('radio9', models.BooleanField(default=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_name', to='survey.ClientSurvey')),
            ],
        ),
    ]
