# Generated by Django 2.0.1 on 2018-02-05 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20180202_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyDesingForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_name', to='survey.ClientSurvey')),
            ],
        ),
        migrations.RemoveField(
            model_name='surveyform',
            name='survey',
        ),
        migrations.DeleteModel(
            name='SurveyForm',
        ),
    ]
